name: Cross-compilation Raspberry Pi

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ragnaroek/rust-raspberry:1.81.0

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Rust build and test
      run: cargo test

    - name: Build cross-compilation binary
      run: cargo build --release

    - name: Upload binary
      uses: actions/upload-artifact@v3
      with:
        name: boiler-watch-api_arm-linux-gnueabihf
        path: target/arm-unknown-linux-gnueabihf/release/boiler-watch-api
