name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run Tests
      run: cargo test

    - name: Set up Rust for Raspberry Pi cross-compilation
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: arm-unknown-linux-musleabihf

    - name: Install dependencies for cross-compilation
      run: sudo apt-get install -y musl-dev

    - name: Build binary for Raspberry Pi
      run: cargo build --release --target=arm-unknown-linux-musleabihf
      
    - name: Upload binary
      uses: actions/upload-artifact@v2
      with:
        name: boiler-watch-api_arm-linux-musleabihf
        path: target/arm-unknown-linux-musleabihf/release/boiler-watch-api
